### PR TITLE
Fix/GRAPH-340

### PR DESCRIPTION
**Pull request by Seb-figment**

### CODE REVIEW

**Review by pienkowb — COMMENTED** [review]
This looks good. @Seb-figment Do you think we could merge this upstream?

**Comment by Seb-figment** [comment]
> This looks good. @Seb-figment Do you think we could merge this upstream?

We can. There is still improvement that need to be done but sending this in chunk would probably ease the process of review upstream.

**Comment by pienkowb** [comment]
> > This looks good. @Seb-figment Do you think we could merge this upstream?
> 
> We can. There is still improvement that need to be done but sending this in chunk would probably ease the process of review upstream.

Alright, are you in contact with the author of the `as-proto` library?

**Comment by Seb-figment** [comment]
> Alright, are you in contact with the author of the `as-proto` library?

Yes. He is aware I'll do a PR shortly. Once this is merge I'll create the PR.

**Review by pienkowb — APPROVED** [review]
LGTM

**Comment by pienkowb** [comment]
BTW, I think we should use a different target branch than `main` (so that `main` always reflects upstream `main`).

**Pull request merged**
